### ISSUE TITLE
Memory Leak or Excessive RocksDB Memory Usage

### ISSUE THREAD

**Issue by 2anoubis** [Taraxa-project/taraxa-node#2959]
# Bug Report

Bug: RocksDB Memory Consumption Unbounded, Leading to Excessive RAM Usage

## Description

The Taraxa node, with built in with RocksDB, does not appear to have memory consumption limits. This results in RocksDB potentially consuming all available system memory, growing to over 70GB in some observed cases.  This behavior makes the node unstable and can lead to server crashes.  We need to expose RocksDB configuration parameters related to memory management to allow operators to control memory usage.

### Steps to Reproduce

1. Run a mainnet registered Taraxa node (v1.12.7) on a server with 64-128GB of RAM.
2. Allow the node to run for approximately two days.

### Expected Result

The node should consume a reasonable and stable amount of RAM, leaving sufficient memory for other system processes.  The memory usage should be configurable and predictable.

### Actual Results

The node consumes all available RAM, in some cases exceeding 70GB. This excessive memory usage leads to performance degradation and potential server instability.

#### Node version
v1.12.7

#### Operating System details.

docker container

**Comment by 2anoubis** [comment]
Starting right now. Will take one day to see difference
Thank you

**Comment by 2anoubis** [comment]
Running official docker images only 
On Kubernetes cluster with my own manifests

**Comment by 2anoubis** [comment]
Not much better v1.12.12

![Image](https://github.com/user-attachments/assets/0491eeb7-5eaa-44dc-b291-cefb2b585ae9)

Already at 20GB in first 24 hours

**Comment by 2anoubis** [comment]
Validators. 
See "Core Block"

**Comment by 2anoubis** [comment]
Build version: 352782c788b5c5447835f78131047ab910182d4d

**Comment by 2anoubis** [comment]
Maybe it trying to use up to available 64GB memory on the instance and  you running it on 8GB instance

**Comment by 2anoubis** [comment]
Given that databases, and RocksDB specifically, are optimized for read operations, and considering that a validator's primary function is block writing (accounting for approximately 99% of its activity), I propose a potential optimization.

During normal operation, validators rarely need to read committed blocks. Read operations are primarily necessary during initial synchronization for new validators. Therefore, it might be beneficial to explore the feasibility of significantly reducing or even disabling the RocksDB cache for validators.

This approach could potentially:

    Reduce overall memory consumption.
    Minimize unnecessary read operations.
    Improve write performance by dedicating more resources to block writing.

Further investigation and testing are needed to determine the potential benefits and any associated risks. However, given the validator's write-heavy workload, it seems a worthwhile area to explore

**Comment by 2anoubis** [comment]
When I refer to 'normal RocksDB operation,' I'm thinking of scenarios like Facebook's, where RocksDB is optimized for a high ratio of read operations to write operations – essentially, one write for millions of reads.

In contrast, a validator's primary activity is block writing, making it a write-heavy workload with minimal read requirements, especially during normal operation. The focus is on sequential writing of blocks and maintaining the chain's state, rather than random read access for data retrieval.

**Comment by VladimirDiamandi** [comment]
I have a similar problem, I run full node and use it as rpc.

docker-compose.yml
```
version: "3"
services:
  node:
    image: taraxa/taraxa-node:v1.12.10
    deploy:
      resources:
        limits:
          memory: 100g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    ports:
      - "10002:10002"
      - "10002:10002/udp"
      - "7777:7777"
      - "8777:8777"
    entrypoint: /usr/bin/sh
    command: >
      -c "mkdir -p /opt/taraxa_data/data &&
          taraxad --chain mainnet --wallet /opt/taraxa_data/conf/wallet.json --config /opt/taraxa_data/conf/mainnet.json --data-dir /opt/taraxa_data/data --overwrite-config --enable-test-rpc"
    volumes:
      - ./config:/opt/taraxa_data/conf
      - data:/opt/taraxa_data/data
  status-app:
    image: taraxa/taraxa-node-status:latest
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - NEXT_PUBLIC_RPC=http://node:7777
    restart: always
    depends_on:
      - node
    ports:
      - "3000:3000"
volumes:
  data:
```

![Image](https://github.com/user-attachments/assets/7b5c9d3e-ca01-4178-891a-b09ca989cb7a)
