### ISSUE TITLE
Dedicated RPC method for liveness and readiness probe

### ISSUE THREAD

**Issue by justinsnapp** [Taraxa-project/taraxa-node#736]
## Is your feature request related to a problem? Please describe.

Right now db initialization can cause a very long delay before standard RPC calls are responsive.

**Comment by rattrap** [comment]
I think we should add a new RPC method called "health" or "healthz".
It should return a "200 OK" status. We don’t necessarily need a specific response.

Example:
```
curl -X POST \
-H 'Content-Type: application/json' \
-d '{"jsonrpc":"2.0","method":"healthz","params": [],"id":1}' https://rpc.testnet.taraxa.io
```

**Comment by sfrique** [comment]
We should work on something that can be verified Kubernetes probes
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes

We should have different endpoints/paths for `Liveness` and `Readiness`

`Readiness Probe` decides to forward traffic or not, `Liveness Probe` decides to restart the Pod or not.

So while db initialization is happening we should not restart the pod, but also not send any traffic.

**Comment by MatusKysel** [comment]
based on this article https://developers.redhat.com/blog/2020/11/10/you-probably-need-liveness-and-readiness-probes#example_4__putting_it_all_together
I think we could do something like they have in example

```
livenessProbe:
  exec:
    command:
    - /bin/sh
    - -c
    - "[ -f /run/nginx.pid ] && ps -A | grep nginx"
  initialDelaySeconds: 10
  periodSeconds: 5
readinessProbe:
  httpGet:
    scheme: HTTPS
    path: /index.html
    port: 8443
  initialDelaySeconds: 10
  periodSeconds: 5
```

but for readiness I would go with our RPC call `taraxa_protocolVersion`, so something like 


```
curl -X POST \
-H 'Content-Type: application/json' \
-d '{"jsonrpc":"2.0","method":"taraxa_protocolVersion","params": [],"id":1}' https://rpc.testnet.taraxa.io
```
